Disabling jog for each deck separately
dan-giddins/mixxx-ddj-200-mapping pull request #11
Opened 2020-10-14 09:49 UTC by fkbreitl

2020-10-14 10:46 UTC, dan-giddins commented on Pioneer-DDJ-200-scripts.js
> +        DDJ200.jog_disabled[deckNumber] = true;
you will also need to check jog_disabled based on deck number

2020-10-14 10:47 UTC, dan-giddins requested changes
you will also need to check jog_disabled based on deck number

2020-10-14 11:03 UTC, fkbreitl reviewed
Yes of course. Thanks for the correction.
Sorry, mistakes happen very easily because they still have not executed our PR and I have to switch back and forth between branches.
I am already working on the 4D (4Decks) branch.
You can have a look. However, I am still struggling with getting the volume mapped in:
https://mixxx.discourse.group/t/mapping-volume-fader-to-javascript-function/20104/
Cheers!

2020-10-14 11:09 UTC, fkbreitl reviewed
fixed jog_disabled[deckNumber]

2020-10-18 13:15 UTC, fkbreitl commented
Hi @Dan, the mapping should be polished now for including in Mixxx. Can you pull it?

2020-10-19 10:21 UTC, dan-giddins approved these changes

2020-10-19 10:24 UTC, merged